Added velocity support
DevLeoko/AdvancedBan pull request #641
Opened 2024-05-13 19:03 UTC by KikyoC

Hello,
I added velocity support and I tested it and it looks working. I checked that the /unban bug (because of not cached) is fixed.

2024-06-21 17:01 UTC, Hopefuls commented
are the changes based off of the development branch?

2024-06-22 08:46 UTC, KikyoC commented
Nope I don't think, you can see here that I'm up to date with leoko dev branch here: https://github.com/KikyoC/AdvancedBan/tree/master

2024-06-30 14:50 UTC, Bensonheimer992 commented
Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned

2024-06-30 15:21 UTC, Hopefuls commented
> Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned

is this related to this pull request? if no then that is known.

2024-06-30 16:10 UTC, KikyoC commented
> Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned

Hello, check this one, I'm waiting they response to open a second pr (because I did something stupid): https://github.com/Swordfun-Server/AdvancedBan

2024-06-30 16:34 UTC, Bensonheimer992 commented
> > Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned
> 
> Hello, check this one, I'm waiting they response to open a second pr (because I did something stupid): https://github.com/Swordfun-Server/AdvancedBan

this version does not work either it still says after banning this player is not banned

2024-06-30 16:42 UTC, KikyoC commented
> > > Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned
> > 
> > 
> > Hello, check this one, I'm waiting they response to open a second pr (because I did something stupid): https://github.com/Swordfun-Server/AdvancedBan
> 
> this version does not work either it still says after banning this player is not banned

I don't have this issue. i'm checking it

2024-06-30 17:04 UTC, KikyoC commented
> > > Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned
> > 
> > 
> > Hello, check this one, I'm waiting they response to open a second pr (because I did something stupid): https://github.com/Swordfun-Server/AdvancedBan
> 
> this version does not work either it still says after banning this player is not banned

I missed something. Should now work (with new release)

2024-07-02 12:13 UTC, Bensonheimer992 commented
can i still use the normal advancedban api or do i have to do something special for it to work with the velocity version ?

2024-07-02 14:33 UTC, Bensonheimer992 commented
> can i still use the normal advancedban api or do i have to do something special for it to work with the velocity version ?

because im trying to use the PunishEvent and nothing happens (i checked that the event is registered)

2024-07-06 08:42 UTC, Bensonheimer992 commented
> > > > Hey every time i ban someone with the Velocity Version of AdvancedBan i have to restart the proxy to unban them if i don't restart the proxy i get the message that this player is not banned
> > > 
> > > 
> > > Hello, check this one, I'm waiting they response to open a second pr (because I did something stupid): https://github.com/Swordfun-Server/AdvancedBan
> > 
> > 
> > this version does not work either it still says after banning this player is not banned
> 
> I missed something. Should now work (with new release)

?

2024-07-07 21:03 UTC, KikyoC commented
Hello, I havent edited anything from the api.

2024-07-08 16:00 UTC, Bensonheimer992 commented
but the event does not get triggered

2024-07-09 12:19 UTC, Bensonheimer992 commented
> Hello, I havent edited anything from the api.

and maybe change the server type from BungeeCord to Velocity

2024-07-12 14:26 UTC, DevLeoko commented
Thanks for your effort to support velocity @KikyoC 
Are the changes from this PR tested and stable? Because you mentioned newer changes and a second PR above.

2024-09-01 09:48 UTC, KikyoC commented
Hey everyone !

I'm sorry if I don't answered on time. I get to many things in my life so that's.

As I said I did something better on https://github.com/Swordfun-Server/AdvancedBan but I meged everything in this repo. I just tried and everything looks good.

2024-09-12 08:34 UTC, nhanledev commented
Hello, I just tested the Velocity support by building  https://github.com/Swordfun-Server/AdvancedBan and run it on my server (velocity only)
- mute, tempmute: OK, player can not send message after being muted
- ban, tempban: OK, player is kicked and can not join the server after being banned

2024-10-06 10:47 UTC, Hopefuls commented
Hello @KikyoC,

wanted to possibly check up on this pr as I will also be testing it on my own soon (thanks @nhanledev for already looking into it).

Though I am still unsure as to how the specific change on the caching resolves the issue with the bans not being correctly handled, do you have some insights into this?

Thank you!

2024-10-06 10:51 UTC, Hopefuls requested changes

2024-10-06 10:51 UTC, Hopefuls commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +import java.io.*;
If possible, please specify which packages from java.io are used (avoid unecessary imports using * wildcards)

2024-10-06 10:53 UTC, Hopefuls commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +
Since this implementation is based off of bukkit, does this work reliably in bungeecord and velocity too?

2024-10-06 10:53 UTC, Hopefuls commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +                logger.warn("Could not save " + outFile.getName() + " to " + outFile + " because " + outFile.getName() + " already exists.");
Remove unnecessary warn when file exists (99% going to be the case after first use)

2025-02-06 20:06 UTC, Bensonheimer992 commented
When does it get merged ?

2025-03-23 18:54 UTC, alfi0812 commented
> When does it get merged ?

When the guy respons to the questions of @Hopefuls. Otherwise it will probably just be closed. He got asked multiple times to respond on Discord and here.

2025-03-23 19:09 UTC, Hopefuls commented
Likely an abandoned pull request due to the lack of responses from the original Creator of the PR

2025-03-25 14:56 UTC, KikyoC commented
Hey, I'm sorry I didn't receive any notification from github about this PR. (Thanks @Bensonheimer992 for dming me on discord). I will take a look about @Hopefuls this evening because I'm at school rn (Paris TZ)

2025-03-25 20:12 UTC, KikyoC commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +
As the comment says, this code is from official bukkit source code. I've never heard any issue with that part of code, so ig it's fine to reuse it in this context

2025-03-25 20:15 UTC, KikyoC commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +                logger.warn("Could not save " + outFile.getName() + " to " + outFile + " because " + outFile.getName() + " already exists.");
As you want. I know that is not really useful, but I thought that it was a good idea to print a log in that case

2025-03-25 20:15 UTC, KikyoC commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +import java.io.*;
Hey I'm sorry about that my IDE replaced every packages

2025-03-25 20:16 UTC, KikyoC commented
So here are the mew updates. It should be fine. If you said something in here and I didn't answer after 24h, do not hesitate to DM me on Discord

2025-03-27 19:32 UTC, Hopefuls commented
I might create a new branch to merge into, the development branch seems to have changes that we wanted to disregard for now.

I'll get back to your if Leoko is fine with that.

2025-03-27 20:47 UTC, Hopefuls commented
Checklist:

- [ ] Bump to Version 2.4.0 (currently 2.3.0) or alternatively 3.0.0 due to this being a entire new major release

2025-03-27 21:05 UTC, Hopefuls commented
Failed to unban a user that was banned in the following way:

- banned the player "0bg" while that player was offline, using /ban 0bg
- tried connecting, failed -> correct behaviour
- trying to use /unban 0bg, failed as stated "player is not banned" -> incorrect behaviour

Behaviour seems to occur when:
- player has been on the server after a restart (join and leave)
- player is not online

This can be fixed by restarting the server, which then allows unbanning the player.

Steps to reproduce:
- have second account join the server
- have second account leave the server
- attempt banning
- observe success
- attempt unbanning
- observe fail
- attempt to restart server
- attempt unbanning
- observe success
- have second account join the server
- can join

![image](https://github.com/user-attachments/assets/a93c0105-c03a-4daa-8ca2-1511d98a1d9a)
![image](https://github.com/user-attachments/assets/b9c63615-7dd3-4c64-9b39-275ebd8057d3)

2025-03-27 21:06 UTC, Hopefuls requested changes
Refer to latest comment

2025-03-28 08:21 UTC, KikyoC commented
Hey, thank you for that report. I'll look it this evening

2025-03-28 09:15 UTC, Bensonheimer992 commented
btw. Server shows BungeeCord instead of Velocity

2025-03-28 11:31 UTC, DevLeoko commented
> I'll get back to you if Leoko is fine with that. I'll be testing this until then though

Ya sure, go ahead @Hopefuls feel free to create, update and rename branches as you see fit. They are currently a bit all over the place due to various abandoned update attempts 

I'd suggest to bump the version to 2.4.0 not 3.0.0

2025-03-28 19:19 UTC, Hopefuls commented
changed branch to "development-future" (Name not final)

2025-03-28 20:21 UTC, KikyoC commented on core/src/main/java/me/leoko/advancedban/utils/Punishment.java
I don;t know why I did this change but that was stupid

2025-03-28 20:25 UTC, KikyoC commented
> btw. Server shows BungeeCord instead of Velocity

Where do you see that ?

2025-03-28 20:27 UTC, KikyoC commented
Note that testing stuff says 
```[ERROR] Failures: 
[ERROR]   PunishmentTest.shouldWorkWithCachedAndNotCachedPunishments:63 Punishment should not be cached if user is not online ==> expected: <false> but was: <true>
```

2025-03-28 21:33 UTC, Hopefuls commented
@DevLeoko can you confirm the testcase of shouldWorkWithCachedAndNotCachedPunishments being intentional like this?

2025-03-28 21:49 UTC, Hopefuls requested changes

2025-03-28 21:49 UTC, Hopefuls commented on bukkit/pom.xml
> +        <version>2.4.0</version>
https://github.com/KikyoC/AdvancedBan/blob/master/velocity/pom.xml#L38-L43

apply like https://github.com/KikyoC/AdvancedBan/blob/master/bungee/pom.xml#L101-L107

2025-03-28 21:55 UTC, Hopefuls commented
> > btw. Server shows BungeeCord instead of Velocity
> 
> Where do you see that ?

This is defined here: https://github.com/KikyoC/AdvancedBan/blob/cecc241c1af2714a9899168bbaf484fd71ec0e34/core/src/main/java/me/leoko/advancedban/utils/Command.java#L514

Possible idea: Implement an enum that defines the type of server instead (this can be dynamically set using the MethodInterface and be used as a getter (conveniently named getServerType) returning said enum

2025-03-28 21:56 UTC, Hopefuls commented
> Hey, thank you for that report. I'll look it this evening

Could no longer reproduce, good job.

I'll further test it tomorrow.

2025-03-28 22:06 UTC, KikyoC commented
> > > btw. Server shows BungeeCord instead of Velocity
> > 
> > 
> > Where do you see that ?
> 
> This is defined here: https://github.com/KikyoC/AdvancedBan/blob/cecc241c1af2714a9899168bbaf484fd71ec0e34/core/src/main/java/me/leoko/advancedban/utils/Command.java#L514
> 
> Possible idea: Implement an enum that defines the type of server instead (this can be dynamically set using the MethodInterface and be used as a getter (conveniently named getServerType) returning said enum

Yeah I'll do that

2025-03-28 22:07 UTC, KikyoC commented on bukkit/pom.xml
> +        <version>2.4.0</version>
Should be done

2025-03-28 22:22 UTC, KikyoC commented
I added server type system with enums. I set isBungee as deprecated (to let time for applications who depend on advanced ban to get updated)

2025-03-29 17:19 UTC, DevLeoko commented
> @DevLeoko can you confirm the testcase of shouldWorkWithCachedAndNotCachedPunishments being intentional like this?

Looks correct to me. The cache should only contain data/punishments for online players, no?

2025-03-29 17:23 UTC, Hopefuls commented
> Looks correct to me. The cache should only contain data/punishments for online players, no?

The behaviour of it seems to be broken, causing recently banned players to not be unbannable. My guess is that punishments should be cached in order to be "unpunished", right?

Refer to https://github.com/DevLeoko/AdvancedBan/pull/641#issuecomment-2759476321 for the issue that causes the non-caching to happen.

2025-03-29 17:28 UTC, DevLeoko commented
> My guess is that punishments should be cached in order to be "unpunished", right?

I don't think so? I mean you should be able to revoke punishments that are not cached, no?

2025-03-29 17:46 UTC, Hopefuls commented
> > My guess is that punishments should be cached in order to be "unpunished", right?
> 
> I don't think so? I mean you should be able to revoke punishments that are not cached, no?

Agreed, though not caching punishments seems to cause issues in the PunishmentRevoke mechanic, which should fetch from the database, which should allow a player to unban someone. This seems to not properly work, causing the issue described in the earlier comment.

The RevokeProcessor uses getPunishments,
(PunishmentManager.java:122)
```java
    public List<Punishment> getPunishments(String target, PunishmentType put, boolean current) {
        List<Punishment> ptList = new ArrayList<>();

        if (isCached(target)) {
            for (Iterator<Punishment> iterator = (current ? punishments : history).iterator(); iterator.hasNext(); ) {
                Punishment pt = iterator.next();
                if ((put == null || put == pt.getType().getBasic()) && pt.getUuid().equals(target)) {
                    if (!current || !pt.isExpired()) {
                        ptList.add(pt);
                    } else {
                        pt.delete(null, false, false);
                        iterator.remove();
                    }
                }
            }
        } else {
            try (ResultSet rs = DatabaseManager.get().executeResultStatement(current ? SQLQuery.SELECT_USER_PUNISHMENTS : SQLQuery.SELECT_USER_PUNISHMENTS_HISTORY, target)) {
                while (rs.next()) {
                    Punishment punishment = getPunishmentFromResultSet(rs);
                    if ((put == null || put == punishment.getType().getBasic()) && (!current || !punishment.isExpired())) {
                        ptList.add(punishment);
                    }
                }
            } catch (SQLException ex) {
            	Universal universal = universal();
                universal.log("An error has occurred getting the punishments for " + target);
                universal.debugSqlException(ex);
            }
        }
        return ptList;
    }
```

This behaviour seems to not work correctly for some reason, as a punishment cannot be found until the server is restarted.

2025-03-29 17:52 UTC, Hopefuls commented
What was the original intention of  PunishmentManager.get().getLoadedPunishments(false).add(this) ? is that the caching for the punishments?

2025-03-29 18:08 UTC, Hopefuls commented
Yeah this is really weird behaviour, which I can't seem to reproduce within the JUnit Tests:

![image](https://github.com/user-attachments/assets/b3eec08d-056b-4a82-a0f7-ce1502b43eac)

RevokeProcessor.java:32 (Keep in mind I've reverted the changes locally regarding that "hotfix" to make it work:

```java
        Punishment punishment = getPunishment(target, type);
        // DEBUG
        System.out.println("Punishment: " + punishment);
        if (punishment == null) {
            MessageManager.sendMessage(input.getSender(), "Un" + type.getName() + ".NotPunished",
                    true, "NAME", name);
            return;
        }
        ```

2025-03-29 18:25 UTC, Hopefuls commented
Issue cannot be reproduced under Bungeecord, so this is likely an issue within Velocity.

2025-03-29 19:03 UTC, Hopefuls commented
the isCached seems to fail on velocity.

Bungeecord:
```
>unban 0bg
20:01:41 [INFO] PunishmentManager.getPunishments: 327c7c5b87964f158ce8056420c2f2c2 BAN true
20:01:41 [INFO] PunishmentManager.getPunishments -> isCached: false
20:01:41 [INFO] PunishmentManager.getBan: [Punishment(name=0bg, uuid=327c7c5b87964f158ce8056420c2f2c2, operator=CONSOLE, calculation=, start=1743274891723, end=-1, type=BAN, reason=none, id=3)]
20:01:41 [INFO] Punishment: Punishment(name=0bg, uuid=327c7c5b87964f158ce8056420c2f2c2, operator=CONSOLE, calculation=, start=1743274891723, end=-1, type=BAN, reason=none, id=3)
20:01:41 [INFO] AdvancedBan » 0bg was successfully unbanned!
```
Velocity:
```
> unban 0bg
[20:02:30 INFO]: PunishmentManager.getPunishments: 327c7c5b87964f158ce8056420c2f2c2 BAN true
[20:02:30 INFO]: PunishmentManager.getPunishments -> isCached: true
[20:02:30 INFO]: PunishmentManager.getBan: []
[20:02:30 INFO]: Punishment: null
[20:02:30 INFO]: §c§lAdvancedBan §8§l» §c§o0bg is not banned!
```

2025-03-29 19:38 UTC, Hopefuls commented
After sitting here looking at it for an hour or two:

Velocity is missing the onDisconnect behaviour that is also implemented on Bungeecord:

https://github.com/KikyoC/AdvancedBan/blob/master/bungee/src/main/java/me/leoko/advancedban/bungee/listener/ConnectionListenerBungee.java

Which is missing here:

https://github.com/KikyoC/AdvancedBan/blob/master/velocity/src/main/java/me/leoko/advancedban/velocity/listener/ConnectionListenerVelocity.java

Implementing this in a similar way to Bungeecord resolved the issue, banning and unbanning works fine after that.

2025-03-29 19:43 UTC, Hopefuls requested changes
refer to previous comment and comments within review.

Thanks for your contribution so far

2025-03-29 19:43 UTC, Hopefuls commented on core/src/main/java/me/leoko/advancedban/utils/Punishment.java
> +        PunishmentManager.get().getLoadedPunishments(false).add(this);
Revert this change, the correct placement is in: https://github.com/DevLeoko/AdvancedBan/blob/2af7d939f608b22715d65a45edb678c0849e5dbc/core/src/main/java/me/leoko/advancedban/utils/Punishment.java#L113

2025-03-29 19:43 UTC, Hopefuls commented on core/src/main/java/me/leoko/advancedban/utils/Punishment.java
> -                PunishmentManager.get().getLoadedPunishments(false).add(this);
Revert this change, the correct placement is in: https://github.com/DevLeoko/AdvancedBan/blob/2af7d939f608b22715d65a45edb678c0849e5dbc/core/src/main/java/me/leoko/advancedban/utils/Punishment.java#L113

2025-03-29 19:43 UTC, Hopefuls commented on core/src/test/java/me/leoko/advancedban/PunishmentTest.java
> -        assertFalse(PunishmentManager.get().getLoadedPunishments(false).contains(punishment), "Punishment should not be cached if user is not online");
Revert this change, this is intentional behaviour

2025-03-29 19:47 UTC, Hopefuls requested changes
Additional changes for broadcastLeoko

2025-03-29 19:47 UTC, Hopefuls commented on velocity/src/main/java/me/leoko/advancedban/velocity/utils/LuckPermsOfflineUser.java
> +package me.leoko.advancedban.velocity.utils;
Please implement broadcastLeoko mechanic to make @DevLeoko happy :)

Example: https://github.com/DevLeoko/AdvancedBan/blob/2af7d939f608b22715d65a45edb678c0849e5dbc/bungee/src/main/java/me/leoko/advancedban/bungee/listener/ConnectionListenerBungee.java#L59-L72

2025-03-29 19:57 UTC, KikyoC commented
I just wanted to know:
Is [that](https://github.com/KikyoC/AdvancedBan/blob/f6784db956708b6fd7db6f45ba21d309422a1798/bungee/src/main/java/me/leoko/advancedban/bungee/listener/ConnectionListenerBungee.java#L59) really useful ?

2025-03-29 20:01 UTC, Hopefuls commented
> I just wanted to know: Is [that](https://github.com/KikyoC/AdvancedBan/blob/f6784db956708b6fd7db6f45ba21d309422a1798/bungee/src/main/java/me/leoko/advancedban/bungee/listener/ConnectionListenerBungee.java#L59) really useful ?


A quote from the broadcastLeoko method:
```
I don't want that there will be any message when the dev of this plugin joins the server! I want this even though the plugin is 100% free and the join-message is the only reward for the Dev :(
```

I do understand this may be too much to have for proxy-based servers, though users can deactivate it if they do not wish to have it. This can be done by creating a readme.txt with that content in it.

Its a simple reward to have for providing AdvancedBan for free. Up to @DevLeoko on that decision though if that should be there or not.

2025-03-29 20:16 UTC, KikyoC commented on velocity/src/main/java/me/leoko/advancedban/velocity/utils/LuckPermsOfflineUser.java
> +package me.leoko.advancedban.velocity.utils;
Added

2025-03-29 20:18 UTC, KikyoC commented
So I let @DevLeoko tell if he wants to let the advertisement when he joins the server

2025-03-29 20:19 UTC, KikyoC commented
With logout event, it looks good for the [mentioned issue](https://github.com/DevLeoko/AdvancedBan/pull/641#issuecomment-2759476321)

2025-03-30 06:51 UTC, DevLeoko commented
> So I let @DevLeoko tell if he wants to let the advertisement when he joins the server

Haha ya, you remove it so it always just sends me a message (`event.getPlayer().sendMessage("§c§lAdvancedBan v2 §8§l» §cHey Leoko we are using your Plugin (NO-BC)");`)

2025-03-30 08:06 UTC, KikyoC commented
> Haha ya, you remove it so it always just sends me a message (`event.getPlayer().sendMessage("§c§lAdvancedBan v2 §8§l» §cHey Leoko we are using your Plugin (NO-BC)");`)

Actually it send "§c§lAdvancedBan §8§l» §7My creator §c§oLeoko §7just joined the game ^^" to all players of the server and "§c§lAdvancedBan v2 §8§l» §cHey Leoko we are using your Plugin (NO-BC)" to you

2025-03-30 12:30 UTC, Hopefuls commented
You can remove the global messages and instead only keep the message sent to leoko directly.

2025-03-30 15:09 UTC, Hopefuls commented
Checking the following features:
- [ ] Exempt perms (LuckPerms Velocity Offline Mode too)
- [ ] Kicking
- [ ] Tempbanning (Issues with times right now, will be handled in separate issue)
- [ ] ipbanning (persistence)

2025-03-30 15:24 UTC, Hopefuls commented
@KikyoC Upon muting a player and having that player try to say something, the following disconnect message ocurrs:

![image](https://github.com/user-attachments/assets/3da69994-2a44-4b60-93e5-01eb4a5173f1)

```
[17:21:42 FATAL]: A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player 0bg
[17:21:42 INFO]: [connected player] 0bg (/[0:0:0:0:0:0:0:1]:38892) has disconnected: A proxy plugin caused an illegal protocol state. Contact your network administrator.
[17:21:42 INFO]: [server connection] 0bg -> lobby has disconnected
```

Is this really not possible within Velocity? Within Bungeecord, this seems possible.

Please look into it

2025-03-30 16:56 UTC, Hopefuls commented
Possible solution:

Require dependency of https://modrinth.com/plugin/signedvelocity when using AdvancedBan on proxy and planning on using the mute feature

2025-03-30 17:26 UTC, Hopefuls commented
@DevLeoko whats your opinion on requiring that dependency for the mute feature within velocity proxy?

2025-03-30 17:56 UTC, KikyoC commented
> @KikyoC Upon muting a player and having that player try to say something, the following disconnect message ocurrs:
> 
> ![image](https://private-user-images.githubusercontent.com/47116705/428406397-3da69994-2a44-4b60-93e5-01eb4a5173f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMzNTc2MDIsIm5iZiI6MTc0MzM1NzMwMiwicGF0aCI6Ii80NzExNjcwNS80Mjg0MDYzOTctM2RhNjk5OTQtMmE0NC00YjYwLTkzZTUtMDFlYjRhNTE3M2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzMwVDE3NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzY2Q2ZWU1ODBiYTVhMWNkMWM2ODc5YjM4YTU3OGFkYmE1ODQ3YmE4ZWJlNDRhYjJhYzc2MzU3NTA2YWI4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TOeWXXKiE9BHnb3SUSczkB_NP-BxWlsMeX_M0fMVazA)
> 
> ```
> [17:21:42 FATAL]: A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player 0bg
> [17:21:42 INFO]: [connected player] 0bg (/[0:0:0:0:0:0:0:1]:38892) has disconnected: A proxy plugin caused an illegal protocol state. Contact your network administrator.
> [17:21:42 INFO]: [server connection] 0bg -> lobby has disconnected
> ```
> 
> Is this really not possible within Velocity? Within Bungeecord, this seems possible.
> 
> Please look into it

Yeah I knew about this error. I'm trying to find a fix for that (I though it was cloudnet issue but it's not)

2025-03-30 18:12 UTC, KikyoC commented
It looks working with signed velocity. I will try to make it so users don't need that plugin

2025-03-30 18:25 UTC, KikyoC commented
It seems that there is no way to avoid this issue without something on backend server

2025-03-30 20:02 UTC, KikyoC commented
From velocity staff: "messing with the chat chain to disable it entirely is not something we really wanna do"

2025-03-31 14:02 UTC, DevLeoko commented
> @DevLeoko whats your opinion on requiring that dependency for the mute feature within velocity proxy? This would be a requirement to run AdvancedBan unter Velocity

If that is a good way to make it work, then I think it should be fine

2025-03-31 14:54 UTC, Hopefuls commented
@KikyoC are you able to implement a sort-of softdepend on velocity? Such as when the server is being started in velocity, add a disclaimer when starting that checks if that plugin is installed. Same with when trying to use any chat-restriction commands such as mute or tempmute. This can be done with a method interface value like "allowMutes" that's set on start.

Thank you for your help!

2025-03-31 21:25 UTC, KikyoC commented
Hey @Hopefuls I'll look into that tomorrow

2025-04-04 17:50 UTC, KikyoC commented
Hey @Hopefuls I'm sorry for late update but I added signedvelocity as soft depend and send a warn into console if [SignedVelocity](https://modrinth.com/plugin/signedvelocity) is not on the server

2025-04-12 15:50 UTC, Hopefuls commented
Hey, sorry for the late reply:

Is it maybe possible to implement in the following way:
- Check if SignedVelocity is installed
- If SignedVelocity: Check if message signing is enabled (secure-profiles iirc)
- if both fail, entirely block the use of the mute feature, such as by erroring out on the mute command.

This is to ensure that confusion would not arise when setting up a velocity server.

2025-04-12 15:57 UTC, Hopefuls commented
Velocity doesn't seem to cancel the chat event correctly, observing the following:

![image](https://github.com/user-attachments/assets/db6dee13-62fd-4178-9dea-0fd5d8753758)
```
[17:55:57 INFO]: Loaded plugin signedvelocity 1.3.0 by 4drian3d
[17:55:57 INFO]: Loaded plugin luckperms 5.4.158 by Luck
[17:55:57 INFO]: Loaded plugin advancedban 2.4.0 by Leoko
[17:55:57 INFO]: Loaded 4 plugins
[17:55:58 INFO]:         __
[17:55:58 INFO]:   |    |__)   LuckPerms v5.4.158
[17:55:58 INFO]:   |___ |      Running on Velocity - Velocity
[17:55:58 INFO]:
[17:55:58 INFO] [luckperms]: Loading configuration...
[17:55:58 INFO] [luckperms]: Loading storage provider... [H2]
[17:55:59 INFO] [luckperms]: Loading internal permission managers...
[17:55:59 INFO] [luckperms]: Performing initial data load...
[17:55:59 INFO] [luckperms]: Successfully enabled. (took 1229ms)
[17:55:59 INFO] [signedvelocity]: Starting SignedVelocity
[17:55:59 INFO]: [AdvancedBan] Offline permission support through LuckPerms active
[17:55:59 INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[17:55:59 INFO] [hsqldb.db.HSQLDB95E79E1502.ENGINE]: checkpointClose start
[17:55:59 INFO] [hsqldb.db.HSQLDB95E79E1502.ENGINE]: checkpointClose synched
[17:55:59 INFO] [hsqldb.db.HSQLDB95E79E1502.ENGINE]: checkpointClose script done
[17:55:59 INFO] [hsqldb.db.HSQLDB95E79E1502.ENGINE]: checkpointClose end
[17:55:59 INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase]: HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
[17:55:59 INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[17:55:59 INFO]:

[]=====[Enabling AdvancedBan]=====[]
| Information:
|   Name: AdvancedBan
|   Developer: Leoko
|   Version: 2.4.0
|   Storage: HSQLDB (local)
| Support:
|   Github: https://github.com/DevLeoko/AdvancedBan/issues
|   Discord: https://discord.gg/ycDG6rS
| Twitter: @LeokoGar
| Update:
|   There is a new version available! [2.3.0]
[]================================[]

[17:55:59 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[17:55:59 INFO]: Done (3.43s)!
[17:56:02 INFO]: [connected player] 0bg (/[0:0:0:0:0:0:0:1]:56506) has connected
[17:56:02 INFO]: [server connection] 0bg -> lobby has connected
> unmute 0bg
[17:56:30 INFO]: §c§lAdvancedBan §8§l» §a§o0bg §7was successfully unmuted!
> mute 0bg
[17:56:35 INFO]: §c§lAdvancedBan §8§l» §c§o0bg §7was successfully muted!
>
```

2025-04-12 16:16 UTC, Hopefuls commented
It seems like SignedVelocity requires Paper to be used on the Backend Servers.

This could be important for later. This is probably why it wasn't entirely enabled on the backend servers.

2025-04-12 16:20 UTC, Hopefuls requested changes

2025-04-12 16:20 UTC, Hopefuls commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMain.java
> +            logger.warn("SignedVelocity is not installed, mute system may kick your players while muted. Please install SignedVelocity to prevent this.");
Further limit the use of the mute feature with this. Refer to my other comment:

> Is it maybe possible to implement in the following way:

> Check if SignedVelocity is installed
If SignedVelocity: Check if message signing is enabled (secure-profiles iirc)
if both fail, entirely block the use of the mute feature, such as by erroring out on the mute command.
This is to ensure that confusion would not arise when setting up a velocity server.

> This could for example be done by implementing a "enableMutes" which is only enforced by velocity, and is simply set to true on everything else by default except Velocity.

2025-04-13 01:39 UTC, 4drian3d commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMain.java
> +    private final Logger logger;
It is unnecessary to add the Inject annotation to a field that is already marked as final and is already being assigned in the constructor that is being injected

2025-04-13 01:39 UTC, 4drian3d commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMethods.java
> +    //Extracted from https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/plugin/java/JavaPlugin.java
We are not in a Bukkit or similar environment and Velocity has Configurate available as a configuration library, there is no need to copy obsolete code from another platform (which could also be improved)

2025-04-13 01:39 UTC, 4drian3d commented on velocity/src/main/java/me/leoko/advancedban/velocity/listener/ChatListenerVelocity.java
> +        if (!event.getMessage().startsWith("/")) {
Velocity is not bungeecord, there is a separate event for command execution, you will never get a command execution using the PlayerChatEvent

2025-04-13 22:13 UTC, KikyoC commented
> It seems like SignedVelocity requires Paper to be used on the backend servers.
> 
> 
> 
> This could be important for later. This is probably why it wasn't entirely enabled on the backend servers.
> 
> 
> 
> Edit: This shouldn't affect AdvancedBan itself though when used in a proxy environment. This should be mentioned on the spigot page when updating @DevLeoko.

Hey sorry for late answer. Yeah it require signed velocity to be installed on proxy and backend servers. I didn't mentioned that sorry

2025-04-15 19:25 UTC, KikyoC commented on velocity/src/main/java/me/leoko/advancedban/velocity/VelocityMain.java
> +    private final Logger logger;
I don't really know where I saw on internet that, but it's a "good practice" to add it here (I've never used that annotation before and I didn't really read the documentation)

2025-06-01 16:24 UTC, Hopefuls commented
Hey @KikyoC, we're still looking into this PR,

there are the following comments on your last commit if you wish to look into it:
https://github.com/DevLeoko/AdvancedBan/pull/641/files/379b140838e54c140501e077d8b7452e79c39d4d#r2040687669
https://github.com/DevLeoko/AdvancedBan/pull/641/files/379b140838e54c140501e077d8b7452e79c39d4d#r2040866574
https://github.com/DevLeoko/AdvancedBan/pull/641/files/379b140838e54c140501e077d8b7452e79c39d4d#r2040866773

2025-09-28 14:55 UTC, closed without merging